### ISSUE TITLE
Campo network tags del mapa

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU_Dataviz#1]
Chicos, hola! Una consulta. La opción network tags del mapa entiendo que se levanta del campo  **Networks you belong to** (que aparece cuando se carga una organización). Quería confirmar esto y si solo levanta la info de ese campo o se nutre de otro más.

Por otro lado les quería pedir el listado de lo que aparece en **"Networks you belong to"** así podemos validarlo.

Beso

**Comment by mtuduri** [comment]
Exacto los network tags se cargan con el campo Networks you belong to.
Basicamente una network vendria a ser un proyecto y esta red esta formada por las organizaciones q son parte de este proyecto, es algo q genera el sistema no deberian preocuparse por eso.

Beso
