### ISSUE TITLE
Campo  Social Area del mapa

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU_Dataviz#2]
Chicos, casi similar consulta a la anterior. El campo **Social Area** del mapa entiendo que levanta los datos de **Areas of impact** cuando se carga un proyecto.

Mi pregunta concreta es si este campo es el que ustedes tienen en la base como **impact tags.**

Por otro lado, el listado del sistema ofrece la opción "Otros" en cuyo caso los usuarios pueden detallar específicamente a qué se refieren con otros. En el mapa esto no aparece y solo figura otros. ¿Es así? Me llama la atención que se pida la especificación y que después no aparezca.

Un beso

**Comment by mtuduri** [comment]
Exacto en la base se llama impact tags

Saludos

**Comment by mtuduri** [comment]
Con respecto a lo de "Otros" se usa para englobar una impact tag q no esta considerado en el listado,
Vendria a ser todos los impac tags q se ingresaron menos los que aparecen en el listado.

Se pide especificacion pq en el detalle del proyecto luego se muestra lo q se ingreso. Por ejemplo:
https://digitalsocial.eu/project/1658 si te fijas "new food consumption" esta area de impacto no aparece en el listado para filtrar, suponente q esa fuera la unica area de impacto q se le seteo.. solo podrias encontrar filtrando usando la opcion "otros" y en el detalle del proyecto podrias ver q fue lo q se puso en otros.
