### ISSUE TITLE
Segunda pantalla del mapa 

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU_Dataviz#3]
Chicos, en la segunda pantalla del mapa (ni bien uno entra) aparece la siguiente imagen:

<img width="856" alt="captura de pantalla 2018-05-27 a la s 13 04 15" src="https://user-images.githubusercontent.com/20649846/40588093-b6f50446-61ae-11e8-90bd-3b6328a696ce.png">

¿Esto lo toma automáticamente la aplicación de las categorías cargadas los formularios? Para saber si al hacer la traducción ahí no es necesaria hacerla acá.

Gracias

**Comment by mtuduri** [comment]
Buenas
Son valores fijos a modo de ejemplo. Yo los traduje pero avisen si quieren cambiarlo por otra cosa.
