### ISSUE TITLE
Documento para traducción mapa

### ISSUE THREAD

**Issue by romicolman** [idatosabiertos/DSI4EU_Dataviz#4]
Chicos, les dejo el link al documento con todas las traducciones del mapa:

https://docs.google.com/document/d/1ETOKgcQIUlmlX_o5kJ3CXmiF8L_nR-JOPqDZBOwRy6A/edit?usp=sharing

Cualquier duda, me escriben por acá :)

Beso

**Comment by mtuduri** [comment]
Quedaron cargadas las traducciones.
Porfvaor reviesen de que este todo bien.
Es posible q algunas cosas permanezcan en ingles, es muy probable q sea algun dato q haya sido dado de alta en la base en ingles, ej el tipo de organizacion.

Si no ven los cambios es muy probable que tengan cacheado el sitio, en tal caso intenten abrirlo en una ventana icognita o borrar la cache de su navegador.

**Comment by romicolman** [comment]
Gracias @mtuduri! Una cosa. En la siguiente pantalla que en vez de etiquetas de redes diga Redes.

![image](https://user-images.githubusercontent.com/20649846/41059101-05643ae8-69a2-11e8-96ac-4d18969ea21b.png)

**Comment by mtuduri** [comment]
Pronto !! :)
